### ISSUE TITLE
The program can't work when   "DenseorNot=false" 

### ISSUE THREAD

**Issue by YinghuiYou** [ygling2008/direct_edge_imu#13]
Thanks  for your work and opening source. 

Some problems ocuured when I runned your code. I changed the value of "DenseorNot" to false in the "MH_01_easy.launch“ file. and then the program performed poorly with large drift. It seems that the Edge-alignment tracker is not stable enough. 
   
And there are many commented code in your project. This realy confuse me. I'm wondering that whether  the executable file compiled from the current project could **reproduce** the results in your first paper. 

What's more, I deleted  “SolveDVO.cpp” and “SolveDVO.h”,  since no references of functions in them were called  in other .cpp files, including "LiveSLAMWrapper.cpp" & "SolveSLAM.cpp". And there are no errors in the compliation. The program also wroked.

**Comment by ygling2008** [comment]
Hi, Yinghui.
Thanks for your time and attention.
I am very sorry for the inconvenience caused while running this code.
For this, I am going to close this repo since I am going on some new work and have no time to maintain it.

Some reponsese for your questions:
The edge alignment module is unstable due to the unconsistency of edge detection among video frames. 
I suggest you try with the state-of-the-art edge detection algoritm using CNNs methods and replace the edge detection module in this program.
This code is a reference implementation of my approach but not the exact implementation used in my paper.
I used to have a had time on improving the edge detection performance when I worked on this approach.
If you get over the edge detection problem, i think you will get similar / better performance than that of reported in my paper.
I want to add a notice that the tracking accuracy of the work is not as good as the state-of-the-art keypoint based methods as stated in the paper, since no bundle adjustments (the key to improve the tracking accuracy) are applied in the optimization.
